#!/usr/bin/env python
import rospy
from web_console import app


def runserver():
    app.run(host='0.0.0.0', port=9999)


if __name__ == '__main__':
    rospy.init_node('web_console')
    runserver()
